# Numpy

 Python is used for multiple purposes, and at most of the time we might deal with complex mathematics formulas and equations. In order to save time in hard coding all those Mathematical equations Python provides Numpy module. Numpy stands for Numerical Python Library, and this is widely used in implementing Neural Networks and in those algorithms where complex mathematics is required. 

### features of numpy 

* Homogeneous Data Structures
* Multidimensional Arrays
* Efficient Data Storage and Access
* Element-Wise Operations

### Install Numpy


pip install numpy

### Load in NumPy

In [5]:
import numpy as np

### Generating Array Using Numpy


In [5]:
array=np.array([2,3,4])

In [6]:
array

array([2, 3, 4])

In [25]:
arr=np.array([2,3,4],dtype='int64')

dtype stands for "data type," and it is a way to specify the type of data that a variable or data structure can hold.

In [27]:
arr

array([2, 3, 4], dtype=int64)

In [28]:
arr.dtype

dtype('int64')

In [29]:
arr.shape

(3,)

In [30]:
arr.size

3

In [22]:
arr = np.random.random(10)
print(arr)

[0.26298762 0.66160896 0.77225089 0.55592088 0.95755991 0.43018921
 0.69035253 0.91287005 0.92609178 0.37090879]


In [5]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
ones=np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
zeros.shape

(2, 5)

In [8]:
zeros.size

10

In [11]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Linspace

In [12]:
lspace=np.linspace(1,5,10)
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Linspace divides a sequence evenly between start and end based on the step value.



In [13]:
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.33511018e-306, 7.56587585e-307, 7.56593017e-307],
       [1.24610383e-306, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22522597e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        6.89805151e-307, 1.78020169e-306, 1.42410974e-306]])

The np.empty() function in NumPy is used to create a new NumPy array without initializing its elements to any specific values. This function allocates memory for the array and returns it, but the values in the array will contain whatever was in that memory location at the time of allocation. 

syntax:np.empty(shape, dtype=float, order='C')


In [15]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

The np.identity() function in NumPy is used to create an identity matrix

In [19]:
ide.shape

(45, 45)

In [42]:
arr=arr.ravel()

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 23, 49, 79])

In [8]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.sum(axis=0)

array([12, 15, 18])

In [47]:
ar.sum(axis=1)

array([ 6, 15, 24])

### Transpose Of The Array


In [48]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transpose of the matrix is the interchange of row and column elements. Transpose of the matrix also effects the shape of an array. For instance if the original array as 3 rows and 2 columns then the transpose of the matrix will have 2 rows and 3 columns.



In [49]:
ar.flat

In [50]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


ar.flat attribute provides a one-dimensional (1D) iterator over the elements of a NumPy array ar. It allows you to access and iterate over the individual elements of the array as if it were flattened into a 1D structure, without actually altering the shape or structure of the original array

### N-Dimensional Arrays


In [10]:
ar.ndim

2

N-Dimensional Arrays means Multiple Dimensional Arrays. Where N is integer value starts from 2 and ends to N(infinity value).




To check the dimension of the numpy array we use ndim attribute.



In [11]:
ar.size

9

### Memory Bytes Of An Array


In [53]:
ar.nbytes

36

nbytes calculates the total bytes used by the elements of the NumPy array.



In [54]:
one=np.array([1,3,4,567,45])
one

array([  1,   3,   4, 567,  45])

### finding the indices of elements

In [56]:
one.argmax()

3

This function returns the index of the maximum value in a NumPy array. If you have an array, it tells you the position of the largest element in that array.

In [57]:
one.argmin()

0

this function returns the index of the minimum value in a NumPy array. It helps you find the position of the smallest element.

In [59]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

The argsort() function returns the indices that would sort an array. In other words, it provides the indices that would rearrange the array in ascending order.

In [62]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [63]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [64]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [65]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

### Generating Random Arrays

In [66]:
arr10 = np.random.random(10)
print(arr10)

[0.47989147 0.27238868 0.75598353 0.4517963  0.12121742 0.45613303
 0.64334531 0.3584882  0.50711655 0.50386917]


np.random.random(): This function generates an array of random numbers from a uniform distribution between 0 and 1.

In [13]:
np.random.rand(10)

array([0.3681971 , 0.38815196, 0.95669437, 0.64289356, 0.38881807,
       0.64425758, 0.65641778, 0.9470266 , 0.96577605, 0.08115839])

In [14]:
np.random.randn(5)

array([-0.96554359, -0.459003  , -0.05026228, -0.58264317, -0.60484294])

np.random.randn(): This function generates an array of random numbers from a standard normal distribution (mean 0, standard deviation 1). 

### Shape And Reshape An Array


In [68]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

ravel is a function that's used to flatten a multi-dimensional array into a one-dimensional array

In [70]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

The reshape function in NumPy  that allows you to change the shape (i.e., the dimensions) of a NumPy array without altering its data. I

In [78]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])
ar2


array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [79]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [80]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [81]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [82]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

The np.where() function takes a condition as an argument and returns the indices where that condition is True. In this case, the condition is ar > 5. It returns the indices of elements in ar that are greater than 5.

In [84]:
type(np.where(ar>5))

tuple

In [85]:
import sys

In [86]:
py_ar=[0,4,552]

In [87]:
np_ar=np.array(py_ar)

In [89]:
sys.getsizeof(1)*len(py_ar)

84

In [94]:
np_ar.itemsize*np_ar.size

12

itemsize gives the memory size of one element of NumPy array in bytes.

